name: Slava Arapov
title: Slava Arapov Notes
email: mail@arapov.net
description: >
  Slava Arapov Knowledge Base and Digital Garden
baseurl: ""
url: "https://notes.arapov.net"
github_username:  slava-arapov
telegram_username: slava_arapov
telegram_channel: arapovblog

plugins:
  - jekyll-last-modified-at

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME

permalink: pretty
relative_permalinks: false

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
